
from bot.locals import Local

LOCAL = Local({
    'WRONG_ROOM' : 'Hello, mate 😎.\n I am not allowed to be in 🏠 here.\nID : <code>{CHAT_ID}</code>',
    'WELCOME_MESSAGE' : "Hello.. 😃 !\nRead 🛃 pinned 📜message for 📮 #RULES and Commands before you do anything.\n\n I can do couple of things:\n\n1. Upload Files from Magnet 🧲 Links.\n2. Upload Files from Direct URL Links.\n3. Upload File as a 📂 Doc.\n4. Upload File as a streaming 📡 File.",
    'PASS_REQUIRED' : '\n\nUse <code>/{cmd_pass} </code>and enter the password.',
    'LEECH_LIST_MESSAGE_HEADER' : '<b>Leech Status</b>',
    'LEECH_LIST_FORMAT' : 'File 📂 Name: <code>{name}</code>\nStatus 💫: {status}\nID 🆔: <code>{gid}</code>\n\n',
    'ARIA2_CHECKING_LINK' : "Checking...🔍",
    'ARIA2_DOWNLOAD_STATUS' : "⏳patience ..let me try 🧑‍💻 to download 📥: <code>{name}</code>\n{block} {percentage}\nFile 📂 Size : {total_size}\nDN Speed ⚡ : {download_speed} / UP Speed ⚡ : {upload_speed}\nSeeders 👨‍👩‍👧 : {seeder}\nETA ⏰: {eta}\nID🆔 : <code>{gid}\n Admin: @leonce8</code>",
    'ARIA2_DOWNLOAD_SUCCESS' : 'File 📂 downloaded Successfully : <code>{name}</code>',
    'ARIA2_DOWNLOAD_CANCELED' : 'Download 🚫 canceled. : <code>{name}</code>',
    'ARIA2_DEAD_LINK' : 'Download 🙅‍♂️auto-canceled 🚫: <code>{name}</code>\nYour File 📂 Torrent🧲/Link is Dead.',
    'ARIA2_NO_URI' : 'Link is ⚠ invalid.',
    'UPLOADING_FILE' : '⏳patience ..let me try 🧑‍💻 to upload 📤: <code>{name}</code>',
    'UPLOADING_PROGRESS' : '⏳patience ..let me try 🧑‍💻 to upload 📤 : <code>{name}</code>\n{block} {percentage}%\nFile 📂 Size : {size}\nUP Speed ⚡: {upload_speed}/s\nETA ⏰: {eta}\n Admin: @leonce8',
    'UPLOAD_FAILED_FILE_MISSING' : ' 📤Upload : ⚠️ Failed. File 📂🚫 not found.\n<code>{name}</code>',
    'GENERATE_THUMBNAIL' : 'Thumbnail : Generating.\n<code>{name}</code>',
    'SPLIT_FILE' : 'File 📁 Splitting ✂ : <code>{name}</code>',
    'SPLIT_FAILED' : '⚠️File 📁 Splitting ✂️: Failed.\n<code>{name}</code>',
    'THUMBNAIL_NO_PHOTO' : 'Set <code>/{cmd_set_thumbnail}</code> as your photo caption.',
    'THUMBNAIL_DOWNLOADING' : 'Downloading thumbnail.',
    'THUMBNAIL_DOWNLOADED' : 'Thumbnail download.',
    'THUMBNAIL_APPLIED' : 'Thumbnail applied.',
    'THUMBNAIL_DELETING' : 'Deleting thumbnail.',
    'THUMBNAIL_RESET' : 'Thumbnail reset.',
    'UPLOAD_AS_DOC' : '📤Upload as 📁document set to {status}.',
    'UPLOAD_AS_ZIP' : '📤 Upload as a zip 🗃 file set to {status}.',
    'TRACKER_RESET' : 'Default torrent tracker reset.',
    'TRACKER_APPLIED' : 'Default torrent tracker applied.',
    'HELP_MESSAGE_HEADER' : '<b>🛃 Here below, are my commands package ❗️</b>',
    'NO_HELP_INFO' : 'no info.',
    'COMMAND_START' : 'start bot',
    'COMMAND_PASSWORD' : 'Enter 🛃 password that is required.',
    'COMMAND_HELP' : 'this message',
    'COMMAND_LEECH' : 'Leech 🧲 Magnet Link or Direct ⛓Link.',
    'COMMAND_CANCEL_LEECH' : 'Cancel 🚫 Leeching',
    'COMMAND_LEECH_LIST' : 'list on-going leech',
    'COMMAND_SET_THUMBNAIL' : 'set custom video thumbnail',
    'COMMAND_RESET_THUMBNAIL' : 'reset custom video thumbnail',
    'COMMAND_UPLOAD_AS_DOC' : 'toggle upload anything as document',
    'COMMAND_UPLOAD_AS_ZIP' : 'toggle upload anything as bundled zipfile',
    'COMMAND_SET_TRACKER' : 'set default tracker, separated by newline',
    'BLOCK_EMPTY' : "▱",
    "BLOCK_FILLED" : "▰"
})